### ISSUE TITLE
Artifact in output N5 for all-zero blocks

### ISSUE THREAD

**Issue by aschampion** [constantinpape/z5#106]
See discovering in funkey/gunpowder#61.

Reduced reproduction:

```py
import numpy as np
import z5py
f = z5py.File('z5pytest.n5', use_zarr_format=False)
b = np.zeros([128, 2345, 2345], dtype=np.uint32)
d = f.create_dataset(name='/test', shape=b.shape, compression='gzip', dtype=np.uint32)
c = np.zeros([32, 1000, 1000], dtype=np.uint32)
c[:, 500:600, 500:600] = 1
d[50:82, 100:1100, 100:1100] = c  # Must be non-block-aligned. Still fine here.
d[82:114, 100:1100, 100:1100] = c  # Now the repeated data will show up.
```

![image](https://user-images.githubusercontent.com/460206/57528483-5b5aaa80-732a-11e9-945a-abf72419faa2.png)

**Comment by aschampion** [comment]
To clarify where the data is being repeated: it's between the chunk boundary and beginning of the slicing in the second write, i.e., from 64:81 in dim 0.

I'm not familiar with `z5`, but from a static readthrough to me it looks like the problem is that when the existing partial chunk is being read in to the buffer [here](https://github.com/constantinpape/z5/blob/475bd98eb402a387db2112c25501a7ae9e4e188f/include/z5/multiarray/marray_access.hxx#L187), because the chunk is empty, `chunkSize` is 0 [here](https://github.com/constantinpape/z5/blob/475bd98eb402a387db2112c25501a7ae9e4e188f/include/z5/dataset.hxx#L529), so none of the existing buffer is overwritten. (I don't get how an exception isn't thrown for the missing chunk, though.) The part of the buffer overlapping with the current write is, though, which is why everything from 82: on is correct.

**Comment by constantinpape** [comment]
Thanks for raising this and for the minimal example.

The file you looked at is not the correct one (it's for a different multi-array version that I am not
using for the python bindings any more).

But I assume that something similar is happening:
The buffer [here](https://github.com/constantinpape/z5/blob/475bd98eb402a387db2112c25501a7ae9e4e188f/include/z5/multiarray/xtensor_access.hxx#L280-L284) is not cleared properly, because of [this check](https://github.com/constantinpape/z5/blob/475bd98eb402a387db2112c25501a7ae9e4e188f/include/z5/multiarray/xtensor_access.hxx#L273).
I think that adding
```
if(chunk.exists()) {
.....
} else {
buffer.fill(0)
}
```
will fix the problem.
I will try it out in the weekend.

**Comment by constantinpape** [comment]
This was indeed caused by the buffer not being cleared for empty chunks.
I have found an easier way to reproduce it and fixed the issue, see [here](https://github.com/constantinpape/z5/blob/master/src/python/test/test_dataset.py#L391-L405).

@aschampion I will try to make a new release including this fix next week.
Would be great if you could check if your actual issue is fixed then (I very much believe so, but would be good to make sure).

**Comment by aschampion** [comment]
I just verified it is indeed fixed! Thanks for the quick turnaround.

While I have you ear, is there a reason LZ4 isn't enabled for conda-forge builds?

**Comment by constantinpape** [comment]
> I just verified it is indeed fixed! Thanks for the quick turnaround.

Thanks for verifying.

> While I have you ear, is there a reason LZ4 isn't enabled for conda-forge builds?

No, just historic reasons (LZ4 tests did not pass when I made the first conda-forge build and I haven't fixed this since then).
I will fix it in the next release.

**Comment by stuarteberg** [comment]
I ran into this today.  Thanks for sorting it out, guys!

And thanks for tagging a new release today, @constantinpape.  I'm looking forward to trying it out as soon as your changes to the conda-forge recipe are ready.

**Comment by constantinpape** [comment]
> And thanks for tagging a new release today, @constantinpape. I'm looking forward to trying it out as soon as your changes to the conda-forge recipe are ready.

I think the conda-forge release is good to go, but I am having the usual confusion with windows builds on azure and appveyor ... If you have any knowledge of this you can speed up the release process @stuarteberg ;).
See https://github.com/conda-forge/z5py-feedstock/pull/13#issuecomment-518317090.

**Comment by stuarteberg** [comment]
>If you have any knowledge of this you can speed up the release process

Sorry, I'm afraid I'm somewhat clueless when it comes to Windows builds...

**Comment by constantinpape** [comment]
> I'm afraid I'm somewhat clueless when it comes to Windows builds...

Same here. Anyway, I hope someone from conda-forge will jump in soon and then I can merge tomorrow.
