### ISSUE TITLE
Mimic open() and h5py.File() file modes

### ISSUE THREAD

**Issue by funkey** [constantinpape/z5#28]
Currently, `n5` datasets are always opened in what would be `r+` for python's `open()` or `h5py`'s `File()`. It would be useful to have `r` (to prevent accidental modification) and `w` (to overwrite existing datasets).

**Comment by constantinpape** [comment]
Yes, I agree.
I haven't implemented this yet, because I would like to do it consistent between the c++ and python API.
I will have a closer look at the issue soon.

**Comment by clbarnes** [comment]
See https://github.com/constantinpape/z5/commit/0d15ea52aeae6595346e3f5d6c5c1acd376f7cf8 for what I'm sure is a very unsafe python-only implementation.

**Comment by clbarnes** [comment]
> The modes x and w- seem to do exactly the same, is this correct ?

Yes, as per the h5py behaviour. Not sure why!

> Isn't this the wrong way round?

Yes - this has actually made me realise that I haven't pushed my latest commits to this branch because I think I'd fixed that already (as well as tidying up the duplication in MUST_EXIST vs CAN_CREATE being exact opposites).

**Comment by constantinpape** [comment]
RIght, now that you say it `MUST_EXIST` and `CAN_CREATE` are indeed exact opposites, I will remove them as well.

**Comment by constantinpape** [comment]
I have finished the implementation of file permissions, see #35 , but haven't merged it yet,
because the error handling is still inconsistent:
python raises `OSErros` for all errors with the permissions, while c++ raises `RuntimeErrors`.
While we could just throw the same kind from both languages, I wonder if this is the right strategy.
For reference, as far as I can tell h5py throws `OSErrors` only if creating / opening the file 
fails and otherwise throws `ValueErrors`.

This is  a symptom of the error handling being currently incosistent in general, see #36 .

**Comment by constantinpape** [comment]
Implemented in 5a8e9b92717363b802f296bc20d0484aea8bf937
