### ISSUE TITLE
Consistent error handling

### ISSUE THREAD

**Issue by constantinpape** [constantinpape/z5#36]
The current error handling is very inconsistent.
The library throws `AssertionErrors`, `RuntimeErrors` and `RangeErrors` without
any clear concept, which to use for which case.
This will only get worse with the introduction of file permissions, see #28 and #35,
which will add `SystemErrors`.

A more consistent error handling / guideline which error to use in which case
would be desirable.
I would highly appreciate any help / input on this issue.

**Comment by clbarnes** [comment]
As far as the python end goes, I guess we can go one of two ways. If we stuck with the h5py anlogy, we'd rethrow OSErrors for stuff relating to the outermost directory (even if it meant catching whatever's coming out of the C++). However, that might get confusing if the OS actually throws an error specific to a single real file inside the directory.

The other way would be custom exceptions, I think (explicit is better than implicit). Maybe they could at least inherit from OSErrors so that anything treating hdf5, n5 and zarr files interchangeably wouldn't break (not that I'm biased, having written a bunch of code which does exactly that...).

Either way, I think wrapping whatever C comes out with is going to be necessary. I *think* python chains tracebacks if you throw a new error from an except clause so that should be fine, in terms of debugging.

Moving away from AssertionErrors is probably for the best - they're convenient but most of them are just checking input values, which I think is meant to be a ValueError (or occasionally a TypeError).

**Comment by clbarnes** [comment]
Just to add to this (mainly so I don't forget it), dealing with OSErrors is a little awkward in cross-compatible code because py3 (rightfully) did away with a bunch of exceptions which mean the same thing: https://docs.python.org/3/library/exceptions.html#OSError

>  I think python chains tracebacks if you throw a new error from an except clause

Still not sure, but you can do it explicitly in a cross-compatible way http://python-future.org/compatible_idioms.html#raising-exceptions

**Comment by constantinpape** [comment]
Thanks for your comments, Chris.
I think the least effort, but still viable solution is to go the same route as h5py and throw OSErrors and 
ValueErrors for the permissions.
Apart from that, I agree that AssertionErrors should be replaced with the proper errors (RuntimeErrors, ValueErrors).
I will have a go at this soon.

**Comment by constantinpape** [comment]
Changed `AssertionErrors` to `ValueErrors` and `RuntimeErrors` in
e7add8547cca50a13dc6f908ff87139f855ac079
