### ISSUE TITLE
Don't write empty chunks

### ISSUE THREAD

**Issue by constantinpape** [constantinpape/z5#39]
Currently, writes to disc are not tested for being empty (i.e. only containing fill-value).
For datasets that contain a lot of empty space, this can create many unnecessary files (which are
very small if compression is used). This can unnecessarily slow down read / write on filesystems that are not designed to deal with this set-up (e.g. Janelia /nrs).

We could implement a check that does not write empty chunks to disc.
However, this cannot be done in a completely naive way.
For example, we have to take into account that the chunk might already contain data on file.
In this case we would need to over-ride this data and delete the chunk.

Also, this might lead to weird behaviour for the zarr format, if we allow to change the fill value for 
a given dataset (though I am not sure if this is something we would want to support).

This issue was raised by @funkey.

**Comment by clbarnes** [comment]
> the chunk might already contain data on file

Once we've detected that the chunk to be written is empty, we don't care about the data on file, do we? So we would just need to try to delete the chunk file, and swallow any `FileNotFoundError`s (or C++ equivalent).

I'm in favour of not supporting changing the fill value. I can't think of a sensible way of dealing with that, unless you represent filled values as different to the value itself e.g. `[1, 2, FILL_ME, 4, 5]` and did the filling every time you read from disc. Otherwise you can't tell the difference between filler values and values which the user intentionally set to something which happens to be equal to the fill.

**Comment by clbarnes** [comment]
Is there anything wrong with an implementation of this along these lines, but in C++?

    def write_chunk(self, data, index):
        if (data == self.fill_value).sum() == data.size:
            os.remove(self.get_chunk_path(index))
        else:
            # do normal writing things

**Comment by constantinpape** [comment]
Yes, that should do it, if we in addition check whether the chunkpath actually exists.
I will try to implement it today.

**Comment by constantinpape** [comment]
Implemented in d952f394ca2b37437499c06e060404e88a29d64d
